[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson  @ ^7.0

build_flags =
    -DWIFI_SSID=\"your_wifi_ssid\"
    -DWIFI_PASS=\"your_wifi_password\"
    -DMQTT_HOST=\"192.168.0.1\"
    -DMQTT_PORT=1883
    -DLOT_ID=\"00000000-0000-0000-0000-000000000000\"
    -DSLOT_LABEL=\"A-01\"
    -DTRIGGER_PIN=5
    -DECHO_PIN=18
